name: Kyrogram Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Build Tools (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxkbcommon-dev libgl1-mesa-dev
      
      - name: Install Build Tools (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake
        
      - name: Build Kyrogram
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
